### ISSUE TITLE
Is it possible provide an option to use either JSON or JSONB?

### ISSUE THREAD

**Issue by anil-resero** [wonderbeyond/SQLAlchemy-Nested-Mutable#1]
Hi,
Thanks for this library which gives clean examples with SQLAlchemy 2.0 mapped_column syntax. Looks like for Postgresql, Pydantic type defaults to JSONB. Is it possible to give the user an option to choose between two, similar to SQLAlchemy?

**Comment by wonderbeyond** [comment]
@anil-resero Sorry for late. I've tried to support customize sqltype with MutablePydanticBaseModel in this commit https://github.com/wonderbeyond/SQLAlchemy-Nested-Mutable/commit/849eaddf5333c4e9dd43df93aced3867331df321
